TITLE 411: PRINT STRING PROGRAM
.MODEL SMALL
.STACK 100H
.DATA
MSG DB 'HELLO!$'
.CODE
MAIN PROC
  ;INITIALIZE DS
    MOV AX,@DATA
    MOV DS,AX
  ;DISPLAY MESSAGE
    LEA DX,MSG
    MOV AH,9
    INT 21H
  ;RETURN TO DOS
    MOV AH,4CH
    INT 21H
MAIN ENDP
    END MAIN