TITLE 412: CASE CONVERSION PROGRAM
.MODEL SMALL
.STACK 100H
.DATA
CR EQU 0DH
LF EQU 0AH
MSG1 DB 'ENTER A LOWER CASE LETTER: $'
MSG2 DB 0DH,0AH,'IN UPPER CASE IT IS: '
CHAR DB ?,'$'
.CODE
MAIN PROC
  ;INIT DS
    MOV AX,@DATA
    MOV DS,AX
  ;PRINT USER PROMPT
    LEA DX,MSG1
    MOV AH,9
    INT 21H
  ;INPUT A CHARACTER AND CONVERT
    MOV AH,1
    INT 21H
    SUB AL,20H
    MOV CHAR,AL
  ;DISPLAY
    LEA DX,MSG2
    MOV AH,9
    INT 21H
  ;DOS EXIT
    MOV AH,4CH
    INT 21H
MAIN ENDP
    END MAIN